modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="the_fe_grid"
version="1.1.51.20.1"
displayName="The FE Grid"
displayURL="https://thefegrid.fatalmistake02.com"
logoFile="logo.png"
credits="MCreator - https://mcreator.net/about"
authors="FatalMistake02"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_fe_grid]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration